language: julia
os:
    - osx
julia:
    - 0.4
    - nightly
notifications:
    email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - git clone https://github.com/chkwon/jpor_codes.git jpor_codes
    - julia -e jpor_codes/test/runtests.jl
